site_name: SlottyMedia Docs
nav:
  - Home: index.md
  - Build: build.md
  - Database: database.md
  - MVVM: mvvm.md
  - Coding Guidelines: guidelines.md
  - Code Documentation: 
    - SlottyMedia: code/SlottyMedia/index.md
    - Database : code/SlottyMedia.Database/index.md
    - Seeding: code/SlottyMedia.DatabaseSeeding/index.md
    - Tests: code/SlottyMedia.Tests/index.md
  - Exception Guidelines: exceptions.md
  - Logging Guidelines : logging.md
theme:
  name: material
  features:
    - instant_navigation
    - content.code.copy
plugins:
  - search
  - include_dir_to_nav
markdown_extensions:
  - pymdownx.extra
  - pymdownx.highlight
  - pymdownx.superfences