name: Run NUnit Tests

on:
  push:
    branches:
      - 'feat/*'
      - 'test/*'
      - 'perf/*'
      - 'style/*'
      - 'fix/*'
      - 'test/*'
      - 'revert/*'
      - 'perf/*'
  pull_request:
    branches:
      - 'feat/*'
      - 'test/*'
      - 'perf/*'
      - 'style/*'
      - 'fix/*'
      - 'test/*'
      - 'revert/*'
      - 'perf/*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Restore tools
      run: dotnet tool restore --tool-manifest ./.config/dotnet-tools.json
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
