name: Run NUnit Tests

on:
  push:
    branches:
      - 'feat/*'
      - 'test/*'
      - 'perf/*'
      - 'style/*'
      - 'fix/*'
      - 'test/*'
      - 'revert/*'
      - 'perf/*'
  pull_request:
    branches:
      - 'feat/*'
      - 'test/*'
      - 'perf/*'
      - 'style/*'
      - 'fix/*'
      - 'test/*'
      - 'revert/*'
      - 'perf/*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      GITHUB_ACTIONS: true

    steps:
    - uses: actions/checkout@v4

	  - uses: supabase/setup-cli@v1
      with:
        version: latest

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Start Supabase
      run: supabase start

    - name: Get Supabase Configuration
      run: |
        export $(grep -v '^#' supabase/.env | xargs)
        echo "SUPABASE_URL=$SUPABASE_URL" >> $GITHUB_ENV
        echo "SUPABASE_KEY=$SUPABASE_ANON_KEY" >> $GITHUB_ENV

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Stop Supabase
      run: supabase stop
